# Generated by Django 5.0.6 on 2024-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_mithilamodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mithilamodel',
            name='type',
            field=models.CharField(choices=[('JNK', 'JANAKPUR'), ('SR', 'SIRAHA'), ('MTR', 'MAHOTTARI'), ('RJB', 'RAJBIRAJ'), ('BTR', 'BIRATNAGAR')], default='JNK', max_length=3),
        ),
    ]
