# Generated by Django 5.0.6 on 2024-07-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_mithilamodel_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mithilamodel',
            options={'ordering': ('place_name',), 'verbose_name_plural': 'Mithila Models'},
        ),
        migrations.RenameField(
            model_name='mithilamodel',
            old_name='name',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='mithilamodel',
            old_name='type',
            new_name='region',
        ),
    ]
