# Generated by Django 5.0.6 on 2024-07-19 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_mithilamodel_descriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
                ('language_origin', models.CharField(max_length=50)),
                ('mithila_place', models.ManyToManyField(related_name='mithila_place', to='core_app.mithilamodel')),
            ],
        ),
        migrations.CreateModel(
            name='MithilaCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceritificate_no', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField()),
                ('mithila_certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core_app.mithilamodel')),
            ],
        ),
        migrations.CreateModel(
            name='MithilaFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodrating', models.IntegerField()),
                ('foodcomment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('mithilafoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mithilafoods', to='core_app.mithilamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
